### ISSUE TITLE
$CXX not set

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/tbb-feedstock#11]
Build fails with:
```python
...
+ cp -r ./include/tbb /home/nwani/m3/conda-bld/tbb_1495998940853/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
_placehold_placehold_placehold_placehold_placehold_placehold_place/include
+ /home/nwani/Downloads/erdc/tbb-feedstock/recipe/tbb_example.c -I/home/nwani/m3/conda-bld/tbb_1495998940853/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
hold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -L/home/nwani/m3/conda-bld/tbb_1495998940853/_b_env_placehold_placehold_placehold_placehold_
placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib -ltbb -o tbb_example
/home/nwani/m3/conda-bld/tbb_1495998940853/work/tbb-2017_U5/conda_build.sh: line 15: /home/nwani/Downloads/erdc/tbb-feedstock/recipe/tbb_example.c: Permission denied
Traceback (most recent call last):
  File "/home/nwani/m3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/build.py", line 1518, in build_tree
    config=config)
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/build.py", line 1143, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/nwani/m3/lib/python2.7/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/nwani/m3/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/nwani/m3/conda-bld/tbb_1495998940853/work/tbb-2017_U5/conda_build.sh']' returned non-zero exit status 1
```

Is `$CXX` supposed to be set by the user?

**Comment by jschueller** [comment]
that should be set by the toolchain package, please provide the full log

**Comment by nehaljwani** [comment]
@jschueller My bad. I didn't have toolchain installed.
